// Build-time icon bundler.
//
// Scans the source tree for Iconify icon names ("prefix:name") and emits a
// single module containing ONLY the icons actually used, resolved to their raw
// SVG data. At runtime these are registered with @iconify/react's store so
// <Icon icon="prefix:name" /> renders inline with no network request.
//
// Run with: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getIconData } from "@iconify/utils";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src");
const OUT = join(SRC, "lib", "generatedIcons.ts");

// Collections referenced in the codebase. Each maps to an @iconify-json/<prefix> package.
const PREFIXES = [
  "solar", "logos", "devicon", "skill-icons", "simple-icons", "ri",
  "vscode-icons", "mdi", "material-symbols", "material-icon-theme",
  "gravity-ui", "svg-spinners", "ph",
];

const ICON_RE = new RegExp(`\\b(${PREFIXES.join("|")}):[a-z0-9]+(?:-[a-z0-9]+)*\\b`, "g");

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(tsx?|jsx?|mdx)$/.test(entry)) out.push(full);
  }
  return out;
}

// 1. Collect every distinct icon name used in source.
const used = new Set();
for (const file of walk(SRC)) {
  const text = readFileSync(file, "utf8");
  for (const match of text.matchAll(ICON_RE)) used.add(match[0]);
}

// 2. Load each collection on demand and resolve icon data.
const collectionCache = new Map();
async function loadCollection(prefix) {
  if (!collectionCache.has(prefix)) {
    const mod = await import(`@iconify-json/${prefix}/icons.json`, { with: { type: "json" } });
    collectionCache.set(prefix, mod.default);
  }
  return collectionCache.get(prefix);
}

// Keep only the fields that belong to IconifyIcon — collections sometimes carry
// extra metadata (e.g. `hidden`) that breaks the strict TS object-literal check.
const ICON_FIELDS = ["body", "left", "top", "width", "height", "rotate", "hFlip", "vFlip"];
function normalize(data) {
  const out = {};
  for (const key of ICON_FIELDS) {
    if (data[key] !== undefined) out[key] = data[key];
  }
  return out;
}

const bundle = {};
const missing = [];
for (const name of [...used].sort()) {
  const [prefix, icon] = name.split(":");
  const collection = await loadCollection(prefix);
  const data = getIconData(collection, icon);
  if (data) bundle[name] = normalize(data);
  else missing.push(name);
}

// 3. Emit the module.
const header = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Run \`npm run icons\` to regenerate after changing icon usage.
import type { IconifyIcon } from "@iconify/react";

export const generatedIcons: Record<string, IconifyIcon> = `;
writeFileSync(OUT, header + JSON.stringify(bundle, null, 0) + ";\n");

console.log(`Bundled ${Object.keys(bundle).length} icons -> src/lib/generatedIcons.ts`);
if (missing.length) console.warn(`WARNING: ${missing.length} icons not found (will fall back to runtime fetch):`, missing.join(", "));
