// Build-time icon bundler.
//
// Scans the source tree for Iconify icon names ("prefix:name") and emits a
// single module containing ONLY the icons actually used, resolved to their raw
// SVG data. At runtime these are registered with @iconify/react's store so
// <Icon icon="prefix:name" /> renders inline with no network request.
//
// Run with: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getIconData } from "@iconify/utils";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src");
const OUT = join(SRC, "lib", "generatedIcons.ts");

// Collections referenced in the codebase. Each maps to an @iconify-json/<prefix> package.
const PREFIXES = [
  "solar", "logos", "devicon", "skill-icons", "simple-icons", "ri",
  "vscode-icons", "mdi", "material-symbols", "material-icon-theme",
  "gravity-ui", "svg-spinners", "ph",
];

const ICON_RE = new RegExp(`\\b(${PREFIXES.join("|")}):[a-z0-9]+(?:-[a-z0-9]+)*\\b`, "g");

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(tsx?|jsx?|mdx)$/.test(entry)) out.push(full);
  }
  return out;
}

// Sections that are code-split with `dynamic(..., { ssr: false })` (see
// LazySections.tsx). Their markup is NEVER server-rendered, so any icon used
// ONLY inside them is never inlined into the SSR HTML — meaning it can be
// registered lazily on the client without risking a hydration mismatch. Icons
// used anywhere else (a server-rendered component, another route) stay eager.
const LAZY_ONLY_FILES = new Set([
  "BlogSection.tsx",
  "TechStackSection.tsx",
  "ProjectsSection.tsx",
  "ServicesSection.tsx",
  "TestimonialsSection.tsx",
  "ContactSection.tsx",
]);

const isLazyOnlyFile = (path) => LAZY_ONLY_FILES.has(path.split("/").pop());

// 1. Collect every distinct icon name used in source, tracking whether each is
//    referenced by any eagerly-rendered (non-lazy) file.
const used = new Set();
const usedEagerly = new Set();
for (const file of walk(SRC)) {
  // Never scan our own generated output — it lists every icon name as a key,
  // which would make every icon look "used eagerly" and defeat the split.
  if (file === OUT) continue;
  const text = readFileSync(file, "utf8");
  const lazy = isLazyOnlyFile(file);
  for (const match of text.matchAll(ICON_RE)) {
    used.add(match[0]);
    if (!lazy) usedEagerly.add(match[0]);
  }
}

// 2. Load each collection on demand and resolve icon data.
const collectionCache = new Map();
async function loadCollection(prefix) {
  if (!collectionCache.has(prefix)) {
    const mod = await import(`@iconify-json/${prefix}/icons.json`, { with: { type: "json" } });
    collectionCache.set(prefix, mod.default);
  }
  return collectionCache.get(prefix);
}

// Keep only the fields that belong to IconifyIcon — collections sometimes carry
// extra metadata (e.g. `hidden`) that breaks the strict TS object-literal check.
const ICON_FIELDS = ["body", "left", "top", "width", "height", "rotate", "hFlip", "vFlip"];
function normalize(data) {
  const out = {};
  for (const key of ICON_FIELDS) {
    if (data[key] !== undefined) out[key] = data[key];
  }
  return out;
}

const critical = {};
const deferred = {};
const missing = [];
for (const name of [...used].sort()) {
  const [prefix, icon] = name.split(":");
  const collection = await loadCollection(prefix);
  const data = getIconData(collection, icon);
  if (!data) {
    missing.push(name);
    continue;
  }
  if (usedEagerly.has(name)) critical[name] = normalize(data);
  else deferred[name] = normalize(data);
}

// 3. Emit the module. Icons are split so `registerIcons` can register the
//    critical set synchronously (needed before hydration) and the deferred set
//    on browser idle, keeping ~KB of icon JSON off the hydration/TBT path.
const header = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Run \`npm run icons\` to regenerate after changing icon usage.
import type { IconifyIcon } from "@iconify/react";

// Icons used by eagerly server-rendered components. Registered synchronously so
// their inline SSR SVG hydrates without a mismatch.
export const criticalIcons: Record<string, IconifyIcon> = ${JSON.stringify(critical, null, 0)};

// Icons used only inside \`ssr:false\` lazy sections. Never in the SSR HTML, so
// they are safe to register on idle after the page is interactive.
export const deferredIcons: Record<string, IconifyIcon> = ${JSON.stringify(deferred, null, 0)};

// Back-compat: the full set, in case anything imports it directly.
export const generatedIcons: Record<string, IconifyIcon> = { ...criticalIcons, ...deferredIcons };
`;
writeFileSync(OUT, header);

console.log(
  `Bundled icons -> src/lib/generatedIcons.ts (critical: ${Object.keys(critical).length}, deferred: ${Object.keys(deferred).length})`,
);
if (missing.length) console.warn(`WARNING: ${missing.length} icons not found (will fall back to runtime fetch):`, missing.join(", "));
